apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-basic-role-binding
  namespace: thermofischer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentlc-manager
subjects:
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops

  